SELECT IIF(LUONG>=LTB,'KHONG TANG LUONG','TANG LUONG') AS THUONG,TENNV,LUONG,LTB
FROM (SELECT TENNV,LUONG,LTB
FROM NHANVIEN,(SELECT PHG,AVG(LUONG) AS 'LTB' FROM NHANVIEN GROUP BY PHG) AS TEMP 
WHERE NHANVIEN.PHG=TEMP.PHG) AS ABC