BEGIN TRY
INSERT PHONGBAN
VALUES (799, 'ZXK-799','2008-07-01','0197-05-22')
PRINT 'SUCCESS: RECORD WAS INSERTED'
END TRY

BEGIN CATCH
PRINT'FAILURE: RECORD WAS NOT INSERTED.'
PRINT ' ERROR'+ CONVERT(VARCHAR,ERROR_NUMBER(),1)
+': ' + ERROR_MESSAGE()
END CATCH
