SELECT THOIGIAN+CAST(PHANCONG.THOIGIAN AS decimal(6,2))
  FROM PHANCONG, DEAN
  
  GO
  SELECT THOIGIAN + CONVERT(decimal(6,2),101)
  FROM PHANCONG, DEAN
  
  GO
  SELECT THOIGIAN+CAST(PHANCONG.THOIGIAN AS VARCHAR)
  FROM PHANCONG, DEAN

   GO
  SELECT THOIGIAN + CONVERT(VARCHAR,101)
  FROM PHANCONG, DEAN