SELECT 
  UPPER (HONV) AS 'HONV', 
  LOWER(TENLOT) AS 'tenlot', 
  LOWER (LEFT(TENNV,1)) + UPPER(SUBSTRING(TENNV,2,1)) + SUBSTRING(TENNV,3,LEN(TENNV)-2), TENNV
  DCHI, COUNT(MANV) AS 'SỐ THÂN NHÂN' FROM NHANVIEN
  GROUP BY HONV, TENLOT, TENNV, DCHI HAVING COUNT(MANV) >= 2
  SELECT DCHI FROM NHANVIEN
  SELECT DCHI,CHARINDEX(' ',DCHI) FROM NHANVIEN
  SELECT DCHI, LEFT(DCHI,CHARINDEX(' ',DCHI)) AS 'SỐ NHÀ'FROM NHANVIEN