SELECT COUNT (MADA)	FROM PHANCONG WHERE MA_NVIEN='001'
SELECT * FROM PHANCONG
IF OBJECT_ID('FN_DEAN_NV') IS NOT NULL
DROP FUNCTION FN_DEAN_NV
GO
CREATE FUNCTION FN_DEAN_NV( @MANHANVIEN NVARCHAR(9))
RETURNS INT
AS
BEGIN
RETURN(SELECT COUNT (MADA)	FROM PHANCONG WHERE MA_NVIEN=@MANHANVIEN)
END
PRINT N'SỐ LƯỢNG ĐỀ ÁN CỦA NHÂN VIÊN :' + CAST (DBO.FN_DEAN_NV('001') AS VARCHAR(5))
SELECT * FROM NHANVIEN 
GO