IF OBJECT_ID('FN_PHAI_NV') IS NOT NULL
DROP FUNCTION FN_PHAI_NV
GO
CREATE FUNCTION FN_PHAI_NV( @GT NVARCHAR(4))
RETURNS INT
AS
BEGIN
RETURN(SELECT COUNT (*)	FROM NHANVIEN WHERE UPPER(PHAI)=UPPER(@GT))
END
SELECT * FROM NHANVIEN
PRINT N'SỐ LƯỢNG NHÂN VIÊN NAM :' + CAST (DBO.FN_PHAI_NV('NAM') AS VARCHAR(5))
PRINT N'SỐ LƯỢNG NHÂN VIÊN NỮ :' + CAST (DBO.FN_PHAI_NV(N'NỮ') AS VARCHAR(5))
GO