IF OBJECT_ID('FN_PB_NV_DEAN') IS NOT NULL
DROP FUNCTION FN_PB_NV_DEAN
GO
CREATE FUNCTION FN_PB_NV_DEAN (@MAPB INT)
RETURNS @LISTPB TABLE (TENPHONG NVARCHAR(20), HOTENNV NVARCHAR(60),SLDUAN INT)
AS 
BEGIN
INSERT INTO @LISTPB
SELECT PHONGBAN.TENPHG, CONCAT(HONV,' ', TENLOT, ' ', TENNV), COUNT(MADA) 
FROM PHONGBAN INNER JOIN DEAN ON DEAN.PHONG=PHONGBAN.MAPHG 
INNER JOIN NHANVIEN ON NHANVIEN.PHG=PHONGBAN.MAPHG 
WHERE PHONGBAN.MAPHG=@MAPB
GROUP BY TENPHG, HONV, TENLOT, TENNV
RETURN
END
SELECT * FROM DBO.FN_PB_NV_DEAN('005');
GO